### ISSUE TITLE
Unable to Enable vanilla tools

### ISSUE THREAD

**Issue by Daenyth** [bonii-xx/IguanaTweaksTConstruct#16]
This might be more of a support request, but what am I missing to enable vanilla tools? Whenever I make for example a stone pickaxe, it has red text saying you can't mine with it.

Do the settings need to be in place before worldgen? I probably ran worldgen with the default (restrict) option. I changed the options after being in my world for a bit.

My configs: https://gist.github.com/Daenyth/2317a42ee12aa7620a49

**Comment by bonii-xx** [comment]
No, these things take effect immediatly. Since both disableStoneTools and disableVanillaTools is false, it should (and in my environment, does) work.
Are you sure you restarted the client to reload the config?

**Comment by Daenyth** [comment]
I've restarted the server multiple times. I'm running forge 1207 with these mods:

```
./1.7.10/CodeChickenLib-1.7.10-1.1.1.93-universal.jar
./appliedenergistics2-rv0-stable-10.jar
./BiblioCraft[v1.7.5][MC1.7.10].jar
./BigReactors-0.4.0rc2.jar
./BiomesOPlenty-1.7.10-2.1.0.969-universal.jar
./Blood Magic-v1.1.0(1.7.10).jar
./CodeChickenCore-1.7.10-1.0.2.9-universal.jar
./CoFHCore-[1.7.10]3.0.0B3-26.jar
./CoFHLib-[1.7.10]1.0.0B3-20.jar
./enderio-2.0_beta.178.jar
./extrautilities-1.1.0g.jar
./IguanaTinkerTweaks-1.7.10-2.0.1B2.jar
./InventoryTweaks-1.58-147.jar
./ironchest-1.7.10-6.0.49.733-universal.jar
./Jabba-1.1.4_1.7.10.jar
./Mantle_mc1.7.10_0.3.0.jar
./MineFactoryReloaded-[1.7.10]2.8.0RC2-572.jar
./neiaddons-mc1710-1.12.0.4.jar
./NEIPlugins-MC1.7.10-1.1.0.7-unofficial.jar
./NetherOres-[1.7.10]2.3.0RC3-84.jar
./NotEnoughItems-1.7.10-1.0.2.15-universal.jar
./OpenBlocks-1.7.10-1.3-snapshot-430.jar
./OpenModsLib-1.7.10-0.6-snapshot-223.jar
./Railcraft_1.7.10-9.2.2.0.jar
./SimplyJetpacks-MC1.7.10-1.1.0.jar
./TConstruct_mc1.7.10_1.6.0d39.jar
./ThermalExpansion-[1.7.10]4.0.0B3-11.jar
./ThermalFoundation-[1.7.10]1.0.0B1-6.jar
./TiC-Tooltips-mc1.7.10-1.1.9.jar
./Waila-1.5.3_1.7.10.jar
```

Here's a copy of the startup logs: https://gist.github.com/Daenyth/fddc91d13ac254093858

**Comment by bonii-xx** [comment]
I don't see the log for nerfing vanilla tools. It's probably either a problem on your side or fixed in the next version. Or you're changing the wrong config files.

**Comment by Daenyth** [comment]
Could this be in `main.cfg` if `allowedtools { S:exclusionType=blacklist; S:mods < minecraft > }`?

**Comment by bonii-xx** [comment]
No, that doesn't have an impact if vanilla tools aren't disabled.

**Comment by Daenyth** [comment]
I'm still experiencing this even creating an entirely new server. I've tried tweaking tons of the settings. Using 2.0.2 now.

**Comment by bonii-xx** [comment]
Create a new server. Minimal instance containing only tinkers, mantle and iguana tweaks. Start once. Go to the newly created ITT/main.cfg and set disableRegularTools to false. Start the server again and see if it works.
